name: Explore Actions
run-name: "${{github.actor}} explores actions"

on: [workflow_dispatch]

jobs:
  Explorer:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is triggered by ${{github.event_name}} event."
      - run: echo "It was triggered on ${{github.ref}} for ${{github.repository}}"
      - run: echo "It is running on ${{runner.os}}"
      - name: Check out repository
        uses: actions/checkout@v6
      - run: echo "Source code has now been checkout on runner"
      - name: List files in source code
        run: |
          ls ${{github.workspace}}
      - run: echo "The job now has a ${{job.status}} status."